lookahead_distance : 1 #forward looking distance 
speed : 0.06 #maximum speed
expansion_size : 3 # wall expansion coefficient 
target_error : 0.15 #margin of error to target
robot_r : 0.4 #safety distance i think
